/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { syncPendingOrders, syncPendingMutations } from '@/lib/sync';

declare const self: ServiceWorkerGlobalScope;

interface SyncEvent extends Event {
    readonly tag: string;
    waitUntil(f: Promise<void>): void;
}

// Take control immediately
self.skipWaiting();
clientsClaim();

// 1. Precache assets generated by Next.js (injected by workbox-webpack-plugin)
precacheAndRoute(self.__WB_MANIFEST);

// 2. Custom Routing (Replicating next.config.ts)

// Health check - Network Only
registerRoute(
    ({ url }) => url.pathname === '/api/health',
    new NetworkOnly()
);

// API Calls - Network First
registerRoute(
    /^https?.+?\/api\/.+$/,
    new NetworkFirst({
        cacheName: 'api-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 24 * 60 * 60 // 1 day
            })
        ]
    })
);

// Navigation (Pages) - Network First
registerRoute(
    ({ request }) => request.mode === 'navigate',
    new NetworkFirst({
        cacheName: 'pages-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 24 * 60 * 60
            })
        ]
    })
);

// Static Assets - StaleWhileRevalidate
registerRoute(
    /^https?.+?\/_next\/static\/.+$/,
    new StaleWhileRevalidate()
);

registerRoute(
    /^https?.+?\.(?:png|jpg|jpeg|svg|webp|gif|ico)$/,
    new StaleWhileRevalidate()
);


// 3. BACKGROUND SYNC LISTENER
self.addEventListener('sync', (event: Event) => {
    const syncEvent = event as SyncEvent;
    if (syncEvent.tag === 'garayi-sync') {
        console.log('[SW] Background Sync Triggered!');
        syncEvent.waitUntil((async () => {
            try {
                const o = await syncPendingOrders();
                const m = await syncPendingMutations();

                if (o.syncedCount > 0 || m.syncedCount > 0) {
                    console.log(`[SW] Sync success: ${o.syncedCount} orders, ${m.syncedCount} mutations`);

                    // Notify clients to refresh UI
                    const clients = await self.clients.matchAll();
                    clients.forEach(client => {
                        client.postMessage({ type: 'SYNC_COMPLETE' });
                    });
                }
            } catch (err) {
                console.error('[SW] Sync failed', err);
            }
        })());
    }
});
